import os

def test(ctx):
    os.chdir('tests')

    ctx.exec_command(['./prefect', os.path.join('build', 'src',
                                                'compiler', 'towel'),
                      os.path.join('build', 'src',
                                   'vm', 'tvm')])
