#! /usr/bin/env python3

def build(b):
    b(features='tex',
      type='xelatex',
      source=['towel.%s.tex' % it for it in ['asm',
                                             'grammar.def',
                                             'manual']],
      outs='pdf',
      prompt=0)
